---
- name: put hadoop-jobhistoryserver-{{ env_name }}.rb eye config file
  template: src=jobhistoryserver.rb dest=/etc/eye/hadoop-jobhistoryserver-{{ env_name }}.rb owner=root group=root mode=0644

- name: load config in eye
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye l /etc/eye/apps.eye"
  become: yes
